### ISSUE TITLE
Wrong language choice

### ISSUE THREAD

**Issue by zetok** [kpp/2tox#3]
> Because we cannot trust the base implementation of toxcore, it lacks tests and code style.

If you're into building trust in code, you most likely have chosen the wrong language to do it.

You might find it useful: [You can't spell trust without Rust](https://cdn.rawgit.com/Gankro/thesis/master/thesis.pdf)

`toxcore` was started when Rust was far from being stable, or AFAICT usable enough to write it in it. As such, it wasn't really a mistake to write it in C. Things have changed though, and currently Rust is more than able to do the job.

Given that, I kinda wonder - is there a point to using a wrong tool (language) in `2tox`?

**Comment by kpp** [comment]
@zetok I love Rust. But we cannot trust the code without unit tests. So the first aim is to rewrite AND understand the code written in old C, the second aim is to fix bugs. You are free to implement parts of code in Rust since there are tests you can rely on.

**Comment by zetok** [comment]
> You are free to implement parts of code in Rust since there are tests you can rely on.

If I understood right, you would be happy to merge PRs with Rust code that would replace current C code in `2tox`?

**Comment by kpp** [comment]
@zetok why not? Keep in mind you should write
- tests using C API (to switch between languages, you may have a look at my tests, they are suitable for old toxcore and for my implementation with modification of only 2 LOC)
- implement a Rust code that somehow provides .h and uses only .h without including local Rust modules. In the future this limitation may be eliminated

**Comment by zetok** [comment]
I see, thanks. I will see whether I can do that (knowledge and experience being the limiting factors), and if I will have anything that would actually work, I'll make PR(s) with it. No promises though :)
